### ISSUE TITLE
wayland: `No available video device` error

### ISSUE THREAD

**Issue by vrutkovs** [flathub/com.github.Anuken.Mindustry#1]
```
flatpak run com.github.Anuken.Mindustry                         
sh: xdg-mime: command not found
[I] Initialized Discord rich presence.
arc.backend.sdl.SDLError: No available video device
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:181)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:80)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:30)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
[I] Sending crash report.
java.net.ConnectException: Network is unreachable (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at arc.util.NetJavaImpl.lambda$http$0(NetJavaImpl.java:67)
	at arc.util.async.AsyncExecutor.lambda$submit$2(AsyncExecutor.java:33)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vrutkovs** [comment]
I'm on Wayland and if its started with `--env=SDL_VIDEODRIVER=wayland` it throws
```
arc.backend.sdl.SDLError: wayland not available
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:181)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:80)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:30)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```

Which is upstream's https://github.com/Anuken/Mindustry/issues/1393

**Comment by muelli** [comment]
so.. is this actionable here? Or is this purely an upstream issue?

**Comment by vrutkovs** [comment]
Seems it needs to be linked to a [custom version of glew](https://github.com/Anuken/Mindustry/issues/1393#issuecomment-596232086) - not sure if its doable or even worth doing

**Comment by TheEvilSkeleton** [comment]
i found a GUI fix for it since i suck with the CLI:

1. install the Flatpak'd package `com.github.tchx84.Flatseal`
2. run it
3. disable `Wayland windowing system` (as shown in the picture below)

![image](https://user-images.githubusercontent.com/50847364/81838787-9d599600-9514-11ea-9a98-4db45687f04d.png)

4. profit

**Comment by vrutkovs** [comment]
Yep, `flatpak override --user --nosocket=wayland com.github.Anuken.Mindustry`

**Comment by TheEvilSkeleton** [comment]
> Yep, `flatpak override --user --nosocket=wayland com.github.Anuken.Mindustry`

thank you for the command. i kept running `flatpak run --socket=wayland com.github.Anuken.Mindustry` and was wondering where i was going wrong lmao
