### ISSUE TITLE
Doesn't work on arm64 despite having package for it

### ISSUE THREAD

**Issue by micr0-dev** [flathub/com.github.Anuken.Mindustry#66]
```
~ ❯ flatpak run com.github.Anuken.Mindustry
[E] arc.util.ArcRuntimeException: Couldn't load shared library 'libarcarm64.so' for target: Linux, 64-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:84)
	at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:14)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:107)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Unable to read file for extraction: libarcarm64.so
	at arc.util.SharedLibraryLoader.readFile(SharedLibraryLoader.java:93)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:253)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 4 more
```

```
OS: Fedora Linux Asahi Remix 40 (Workstation Edition) aarch64 
Host: Apple MacBook Air (13-inch, M2, 2022) 
Kernel: 6.8.10-400.asahi.fc40.aarch64+16k 

Packages: 2074 (rpm), 19 (flatpak) 
DE: GNOME 46.2 
```

Arm package should probably be removed until the project actually supports it

**Comment by TobTobXX** [comment]
Huh, I'm not too sure, but I thought it was java / libGDX and thus crossplatform. Is libGDX not on arm...?

**Comment by k8ieone** [comment]
It is unfortunate, but the developer is complstely uninterested in bringing ARM support. There were a lot of issues open in the upstream repo about ARM support. All of them end like this one https://github.com/Anuken/Mindustry/issues/4854

**Comment by k8ieone** [comment]
The game uses a game framework based on libGDX called arc. https://github.com/Anuken/Arc/issues/167 This is the real blocker.

**Comment by TobTobXX** [comment]
Ok, thanks for collecting the links/infos. Submitted a PR to fix this. If aarch64 will be supported in the future, a new issue can be opened.

(btw, the issue may just go away if we can someday build it from source. It is not clear whether there are actual build issues when building for aarch64, there was an attempt, but I abandoned it because gradle is a PITA to generate flatpak modules from.)

**Comment by k8ieone** [comment]
Building from source is preferred for Flatpak afaik, but I get it. IIRC I tried building the game on bare metal on x86_64 at some point but eventually gave up as well.

**Comment by k8ieone** [comment]
I couldn't let it go so I tried getting an ARM build going today. My Arc fork with the necessary changes is here: https://github.com/k8ieone/Arc

I also found https://github.com/flatpak/flatpak-builder-tools/tree/master/gradle which means we should be able to build the Flatpak from source.

So far I was able to generate resources for both Arc and Mindustry. Unfortunately I wasn't able to generate it from the last release tag, only from the master branch. But at least it's a start. I'll try to move this along and modify the Flatpak manifest to build from source hopefully later this week.

You can find the generated resources in my fork: https://github.com/k8ieone/com.github.Anuken.Mindustry

Unfortunately I wasn't able to test the built jar file on my hardware. All my ARM systems run Alpine [which is not supported](https://github.com/Anuken/Mindustry/issues/10258) so I won't be able to try this until I'm able to run it in Flatpak to avoid the musl incompatibility.

**Comment by TobTobXX** [comment]
Wow, nice job getting Arc to compile on aarch64 too! Did you get it to work outside of Flatpak? If yes, then it would be nice if you submitted the PR to Arc.

A few years ago I already tried building the Flatpak from source (#39). The gradle module from flatpak-builder-tools was still a PR then and I used a modified script instead (instead of parsing the gradle stdio output, I tried listing the gradle cache after a build). However Mindustry uses (used?) some weird dynamic dependency injection and the build tool didn't catch on. I'd recommend to not get your hopes high before you can test the flatpak.

**Comment by k8ieone** [comment]
Damn, thanks for letting me know.

About Arc, I did some more thinking on this and in its current state it needs to be built *on ARM* because I had issues getting SDL2 cross-compiled.

If we're able to solve this one little problem, I can see this getting accepted as a PR.

**Comment by TobTobXX** [comment]
> I had issues getting SDL2 cross-compiled.
I've never _not_ had isssues with cross-compiling :).

> it needs to be built on ARM
> If we're able to solve this one little problem, I can see this getting accepted as a PR.
Hmm... Well GitHub has ARM-runners, so the CI would (should) actually work if it works on your machine. Maybe try running the GitHub actions on your own account and check if the generated jar is working on arm. If this works, it is possible that the PR can still be accepted, even though x-compiling doesn't work.

**Comment by k8ieone** [comment]
Good point, I'll try that out.

**Comment by k8ieone** [comment]
@TobTobXX I managed to work around the SDL cross-compile by using an ARM Docker container for the SDL build. The rest of the libraries cross-compile nicely.

I left a [comment](https://github.com/Anuken/Arc/issues/167#issuecomment-2440092875) in the Arc repo.

**Comment by k8ieone** [comment]
@TobTobXX Do you have a device that is a bit more modern where you could test it? The only device where I can easily try this is a Pinephone. I got `GLXBadFBConfig` which could be caused by the Pinephone's outdated hardware.

GitHub didn't allow uploading it here, so here's a link to a file share.

https://cloud.mcld.eu/s/zwAgBwL7fEQjSAs

**Comment by k8ieone** [comment]
Alright, I did some more digging and found `LIBGL_ALWAYS_SOFTWARE=true`, using this I was able to force software rendering and it works! This leads me to believe that the issues I encountered above were indeed caused by ancient hardware.

**Comment by k8ieone** [comment]
Jumping through a whole bunch of hoops, I was eventually able to launch the game inside an ARM Docker container running on my x86 PC as well.

[Screencast From 2024-10-27 20-11-13.webm](https://github.com/user-attachments/assets/05022212-115e-4c3e-8e79-1dbb1d013e6b)

Of course it was extremely slow. Not only was it using software rendering (the ARM build of Mesa didn't have support for Iris graphics, because why would it xd) but it was going through QEMU so the emulation overhead killed it even more. But it works.

**Comment by TobTobXX** [comment]
Wait... you can run Docker apps with a GUI???

But well done! Unfortunately I don't have any ARM devices. @micr0-dev opened the issue, so I suppose they have an arm-device. @micr0-dev if you could help k8ieone test this, that'd be nice.

**Comment by micr0-dev** [comment]
yeah I do! I have an m2 macbook air running asahi linux fedora, i could test it! 

I have both hyprland and gnome installed on it

**Comment by k8ieone** [comment]
@TobTobXX It's janky, but you can :smile: 

@micr0-dev Awesome! I feel like I should warn you about installing random packages from the internet :sweat_smile: 

You can check the Flatpak's permissions by opening it in GNOME Software. I left them the same as the currently published Flatpak and those seem pretty tight to me.

Pinky promise it won't do anything evil :wink:

**Comment by Br0ad** [comment]
I have hardware rendering support on the Raspberry Pi 4 if that helps. @k8ieone 
![20241114_13h56m48s_grim](https://github.com/user-attachments/assets/b30088c5-e7a8-4cf3-abe5-9d967a8497a4)

**Comment by Br0ad** [comment]
@k8ieone I was not expecting high performance in the first place... but turning off effects will have it average around ~50-80 fps in multiple different maps I tested. I will note I dedicated a bit more vram (256mb total now) to the Pi 4's Broadcom VideoCore VI, but otherwise nothing else!

**Comment by k8ieone** [comment]
That's awesome! Thanks for testing it out!

**Comment by Br0ad** [comment]
any time!

**Comment by k8ieone** [comment]
PR is open :rocket:  https://github.com/Anuken/Arc/pull/181

**Comment by TheEvilSkeleton** [comment]
@k8ieone you absolute legend, thanks a lot for working on it! For the record, I have a Xiaomi Redmi 5 Plus running postmarketOS, so I'll be able to test Mindustry on my phone once the arm64 package is working and submitted as a PR :)

**Comment by k8ieone** [comment]
My PineTab 2 just arrived and I was able to properly test this myself. I was really excited to see the game launch and run smoothly on an ARM device.

That being said, Mindustry doesn't expect touch input on Linux devices. Navigating around menus works as expected but touch gestures like pinch zooming are ignored. Dragging in game is the same as clicking and holding with a mouse so there's no way to move around. The game tells you to use WASD to move around :smile: So currently the game is unplayable without a mouse and keyboard. A gamepad sounds like the most portable option but I'm not sure if those are supported by the game, I haven't tested that yet.

I'm thinking even when the PR gets merged, we'll have to wait until the next release before the ARM natives get included. We could "patch" the jar file here on Flathub to include them, but I don't know if that's going to work. The current Mindustry wasn't built against Arc main so there's going to be a version mismatch.

I'll try to come up with a PR that includes the ARM natives in the latest Mindustry release. When the next version comes out we can remove this workaround.

**Comment by k8ieone** [comment]
Quick update: I tried using my Arc build with the latest Mindustry release and it doesn't work. I guess we'll have to wait until the next release.

**Comment by askorbinovaya-kislota** [comment]
> So currently the game is unplayable without a mouse and keyboard.

try with Vars.mobile=true or Vars.testMobile=true

**Comment by askorbinovaya-kislota** [comment]
i tried to set this in js console, but interface didn't change
then i tried mod named "mobile-ui", and it worked

https://github.com/user-attachments/assets/51a2d73a-1ac6-495f-b653-ec4cb10730cc

but game still thinks i have mouse and zooming does not work (x11 limitation, maybe?)

**Comment by Br0ad** [comment]
@askorbinovaya-kislota I will say on my amd64 tablet running kde wayland, mindustry with the mobile ui mod works great but still no zooming here

**Comment by life00** [comment]
For folks using nix, feel free to use this nix code snippet. Just put it into a folder called `default.nix` and import it as a custom package `pkgs.callPackage ../pkgs/mindustry { };`. The default nix package doesn't build on linux aarch64, but this code patches the problematic parts.

```nix
{
  mindustry,
}:

let
  client = mindustry.override { enableServer = false; };
in
  client.overrideAttrs (old: {
    pname = "mindustry-aarch64";

    # Arc declares addLinux(x64, ARM) for arc-core, freetype and filedialogs but
    # not for backend-sdl, so no aarch64 desktop natives exist upstream and
    # nixpkgs marks the client broken here. Retarget backend-sdl's sole Linux
    # target; jnigen then emits libsdl-arcarm64.so into libs/linuxarm64, which is
    # what Arc's SharedLibraryLoader.mapLibraryName looks for at runtime.
    postPatch = old.postPatch + ''
      substituteInPlace ../Arc/backends/backend-sdl/build.gradle \
        --replace-fail 'addLinux(x64, x86){' 'addLinux(x64, ARM){' \
        --replace-fail '"libs/linux64"' '"libs/linuxarm64"'
    '';

    # jnigen hardcodes compilerPrefix = "aarch64-linux-gnu-" for its Linux ARM64
    # target; the native aarch64 stdenv only ships unprefixed tools.
    preBuild = ''
      mkdir -p "$NIX_BUILD_TOP/toolchain"
      for t in gcc g++ ar strip ld nm ranlib; do
        ln -sf "$(command -v $t)" "$NIX_BUILD_TOP/toolchain/aarch64-linux-gnu-$t"
      done
      export PATH="$NIX_BUILD_TOP/toolchain:$PATH"
    '';

    buildPhase =
      builtins.replaceStrings
        [ "jnigenBuildLinux_x86_64" "libs/linux64/" ]
        [ "jnigenBuildLinux_Arm_64" "libs/linuxarm64/" ]
        old.buildPhase;

    meta = old.meta // {
      broken = false;
    };
  })
```
